services:
  filewatcher:
    build:
      context: .
      dockerfile: Dockerfile
      ssh:
        - default
    container_name: Filewatcher
    env_file:
      - .env
    volumes:
      - ./:/app
      - ${HOST_DATA_DIRECTORY}:/app/data
    # networks:
    #   - data_automation
